_wandb:
    value:
        cli_version: 0.21.3
        e:
            y3pcmbxn13d28bleknovrccpggx14f9d:
                codePath: YOLOv8/YOLOv8_bbox_train.py
                codePathLocal: YOLOv8_bbox_train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "38029512704"
                email: kinox1010@gmail.com
                executable: /home/junoh/miniconda3/envs/torch_env/bin/python
                git:
                    commit: 8d10a00de22c6da42ce490e3d76c2c0d2e77b00f
                    remote: https://github.com/TeamFinSight/FinSight-OCR-kinox1010.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-3326e936-bef8-bcd0-08ef-3ea3b26eeabb
                host: DESKTOP-H03BM8F
                memory:
                    total: "33500078080"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /mnt/c/Users/KINOX/Documents/GitHub/FinSight-OCR-kinox1010/YOLOv8/YOLOv8_bbox_train.py
                python: CPython 3.10.18
                root: /mnt/c/Users/KINOX/Documents/GitHub/FinSight-OCR-kinox1010/YOLOv8
                startedAt: "2025-09-01T11:57:42.218062Z"
                writerId: y3pcmbxn13d28bleknovrccpggx14f9d
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
architecture:
    value: yolov8n.pt
batch_size:
    value: 4
epochs:
    value: 10
image_size:
    value: 640
