_wandb:
    value:
        cli_version: 0.21.3
        e:
            nzvkqcob3w1aih2wojxtkue81ehhn3zp:
                codePath: SwinTransformer_NaverClova-ix/Donut_train.py
                codePathLocal: Donut_train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "34388586496"
                email: kinox1010@gmail.com
                executable: /home/junoh/miniconda3/envs/torch_dount_env/bin/python
                git:
                    commit: 9eb7794fd8175f769b6fff2f92893f540586bd53
                    remote: https://github.com/TeamFinSight/FinSight-OCR-kinox1010.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-3326e936-bef8-bcd0-08ef-3ea3b26eeabb
                host: DESKTOP-H03BM8F
                memory:
                    total: "33500094464"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /mnt/c/Users/KINOX/Documents/GitHub/FinSight-OCR-kinox1010/SwinTransformer_NaverClova-ix/Donut_train.py
                python: CPython 3.10.18
                root: /mnt/c/Users/KINOX/Documents/GitHub/FinSight-OCR-kinox1010/SwinTransformer_NaverClova-ix
                startedAt: "2025-09-02T05:28:18.821955Z"
                writerId: nzvkqcob3w1aih2wojxtkue81ehhn3zp
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.3
            "6": 4.42.4
            "12": 0.21.3
            "13": linux-x86_64
effective_batch_size:
    value: 8
epochs:
    value: 50
learning_rate:
    value: 1e-05
physical_batch_size:
    value: 1
