_wandb:
    value:
        cli_version: 0.21.3
        e:
            91nz9fulb7jgiu7jskvqa1xcxji2ze4i:
                codePath: ResNet34RetinaNet/Retina_Resnet34_train_speed_18.py
                codePathLocal: Retina_Resnet34_train_speed_18.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "42113413120"
                email: kinox1010@gmail.com
                executable: /home/junoh/miniconda3/envs/torch_dount_env/bin/python
                git:
                    commit: 71fe1a81d7274125df796be6bf57a5298bc264b2
                    remote: https://github.com/TeamFinSight/FinSight-OCR-kinox1010.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-3326e936-bef8-bcd0-08ef-3ea3b26eeabb
                host: DESKTOP-H03BM8F
                memory:
                    total: "33500086272"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /mnt/c/Users/KINOX/Documents/GitHub/FinSight-OCR-kinox1010/ResNet34RetinaNet/Retina_Resnet34_train_speed_18.py
                python: CPython 3.10.18
                root: /mnt/c/Users/KINOX/Documents/GitHub/FinSight-OCR-kinox1010/ResNet34RetinaNet
                startedAt: "2025-09-04T07:15:45.870202Z"
                writerId: 91nz9fulb7jgiu7jskvqa1xcxji2ze4i
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
            "2":
                - 1
                - 11
                - 41
                - 49
            "3":
                - 13
                - 16
                - 61
            "4": 3.10.18
            "5": 0.21.3
            "6": 4.42.4
            "12": 0.21.3
            "13": linux-x86_64
batch_size:
    value: 12
epochs:
    value: 10
learning_rate:
    value: 0.0002
optimization:
    value: ultra_fast_local_cache_with_perf_metrics
