_wandb:
    value:
        cli_version: 0.21.3
        e:
            e2wdlhh1pqo44fxws9xh7j6vrbsvefro:
                codePath: ResNet50_DETR/DETR_bbox_train.py
                codePathLocal: DETR_bbox_train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "38645014528"
                email: kinox1010@gmail.com
                executable: /home/junoh/miniconda3/envs/torch_env/bin/python
                git:
                    commit: fe6c85cd537785d3b3a6770c22f7f20cb354e6e0
                    remote: https://github.com/TeamFinSight/FinSight-OCR-kinox1010.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-3326e936-bef8-bcd0-08ef-3ea3b26eeabb
                host: DESKTOP-H03BM8F
                memory:
                    total: "33500094464"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /mnt/c/Users/KINOX/Documents/GitHub/FinSight-OCR-kinox1010/ResNet50_DETR/DETR_bbox_train.py
                python: CPython 3.10.18
                root: /mnt/c/Users/KINOX/Documents/GitHub/FinSight-OCR-kinox1010/ResNet50_DETR
                startedAt: "2025-09-02T02:02:28.186823Z"
                writerId: e2wdlhh1pqo44fxws9xh7j6vrbsvefro
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 63
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 63
                - 71
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.3
            "6": 4.56.0
            "12": 0.21.3
            "13": linux-x86_64
batch_size:
    value: 4
epochs:
    value: 10
learning_rate:
    value: 0.0001
